### ISSUE TITLE
dtags edit throws traceback

### ISSUE THREAD

**Issue by F3nr1s** [joowani/dtags#3]
Hi,

I tried dtags today and so far, it seems really nice :-)

But as I tried the "dtags edit" command I got following traceback:
$ dtags edit
Traceback (most recent call last):
  File "/usr/bin/dtags", line 9, in <module>
    load_entry_point('dtags==2.0.0', 'console_scripts', 'dtags')()
  File "/usr/lib/python3.5/site-packages/dtags/commands/manage.py", line 208, in main
    _edit(tail)
  File "/usr/lib/python3.5/site-packages/dtags/commands/manage.py", line 63, in _edit
    tfile.write(EDIT_HELP_COMMENTS + mapping_file.read())
  File "/usr/lib/python3.5/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'

My $EDITOR ist set in the ~/.bashrc:
$ echo $EDITOR
/usr/bin/emacs -nw

(it also works, with every over programm, which calls the $EDITOR variable)

I'm using Arch Linux and have installed dtags through AUR.

It isn't a real problem for me (because I think, I can directly change the files in ~/.dtags), but I think, you are probably interested in this error.

If you need some other information, I'm happy to provide them.

Sincerely

**Comment by joowani** [comment]
Thx for the bug report.

I push another release v2.0.1 just now.
Could you try `pip install --upgrade dtags` and try again? Thanks.

**Comment by F3nr1s** [comment]
Hi,

got the new version, and tried it.
Like I said, my $EDITOR variable is set to
"/usr/bin/emacs -nw".
If I call dtags edit, the following traceback happens:
Traceback (most recent call last):
  File "/usr/bin/dtags", line 9, in <module>
    load_entry_point('dtags==2.0.1', 'console_scripts', 'dtags')()
  File "/usr/lib/python3.5/site-packages/dtags/commands/manage.py", line 213, in main
    _edit(tail)
  File "/usr/lib/python3.5/site-packages/dtags/commands/manage.py", line 77, in _edit
    sp.check_call([editor, tfile.name])
  File "/usr/lib/python3.5/subprocess.py", line 579, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/emacs -nw'

BUT if I change my $EDITOR to /usr/bin/emacs (without the -nw-parameter), it works perfectly.

**Comment by joowani** [comment]
H again,

I've pushed another fix (version 2.0.2) which should now properly handle the variable with multiple arguments. Could you please try again with emacs -nw? Thanks for your patience.

**Comment by F3nr1s** [comment]
Hi,

I have tried it, and it works now with and without parameters.

Thanks for fixing this :-)

**Comment by joowani** [comment]
Np! thanks for trying out dtags and feel free to shout if there are any more problems :)
