### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by jetm** [joowani/dtags#4]
```sh
$ dtags edit
Traceback (most recent call last):
  File "/usr/bin/dtags", line 9, in <module>
    load_entry_point('dtags==2.0.0', 'console_scripts', 'dtags')()
  File "/usr/lib/python3.5/site-packages/dtags/commands/manage.py", line 208, in main
    _edit(tail)
  File "/usr/lib/python3.5/site-packages/dtags/commands/manage.py", line 63, in _edit
    tfile.write(EDIT_HELP_COMMENTS + mapping_file.read())
  File "/usr/lib/python3.5/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```
It happens with Python 3.5, no problem with Python 2.7.

**Comment by joowani** [comment]
Thx for the bug report.

I push another release v2.0.1 just now.
Could you try `pip install --upgrade dtags` and try again? Thanks.

**Comment by joowani** [comment]
Merging this issue (duplicate) into [#3](https://github.com/joowani/dtags/issues/3)

**Comment by jetm** [comment]
I tried and no error with Python v3.5. Thank you for fix it and your quick response.

**Comment by joowani** [comment]
Np! Thanks for trying out dtags.
